config/routes.rb
Rails.application.routes.draw do
  resources :archives
  devise_for :users
  root to: 'articles#index'

  resources :articles
  resources :legislations
  resources :users
  resources :comments

  get 'archives/:id/make_comments' => "archives#make_comments", as: :make_comments
  get 'archives/:id/make_articles' => "archives#make_articles", as: :make_articles

  get 'articles/API/:number/:legislation' => "articles#api_request", as: :retrieve_api_data
  get 'leg/API' => "legislations#api_request", as: :legislation_api_request

  get '/gil' => 'admin#index', as: :admin_path
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_action :admin_only

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @article = Article.find_by_id(@comment.article_id)    
    @comment.content = File.read("#{Dir.pwd}/public/comments/#{@article.id}#{@comment.id}.txt")
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to admin_path_url, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @article = Article.find_by_id(@comment.article_id)    
    File.write("#{Dir.pwd}/public/comments/#{@article.id}#{@comment.id}.txt", params[:comment][:content])
    @comment.content = ""
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to admin_path_url, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to admin_path_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs   
    = f.input :content, label: "Comentário", input_html: { style: "min-height: 500px" }

  .form-actions
    = f.submit "Atualizar comentário", class: "btn btn-success"

app/views/comments/edit.html.haml
.container{style: "max-width:600px"}
  .card
    .card-body
      %h1 Editar comentário
      %hr/
      = render 'form'
      %hr/
      = link_to fa_icon("arrow-left", text: "Voltar", style: "color:black"), articles_path, style: "color:black"

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Article
      %th Content
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.article
        %td= comment.content
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Article:
  = @comment.article
%p
  %b Content:
  = @comment.content

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path