config/routes.rb
Rails.application.routes.draw do
  resources :archives
  devise_for :users
  root to: 'articles#index'

  resources :articles
  resources :legislations
  resources :users
  resources :comments

  get 'archives/:id/make_comments' => "archives#make_comments", as: :make_comments
  get 'archives/:id/make_articles' => "archives#make_articles", as: :make_articles

  get 'articles/API/:number/:legislation' => "articles#api_request", as: :retrieve_api_data
  get 'leg/API' => "legislations#api_request", as: :legislation_api_request

  get '/gil' => 'admin#index', as: :admin_path
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :legislation

  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true

  before_save :insert_br

  def insert_br
    self.content.gsub("         ", "\n")
    self.number.delete! 'º'
    self.number.delete! 'A'
    self.number.delete! 'r'
    self.number.delete! 't'
    self.number.delete! '.'
    self.number.delete! ' '
  end

  filterrific(
   default_filter_params: { sorted_by: 'content_asc' },
   available_filters: [
     :sorted_by,
     :legislation,
     :search_query
   ]
 )

 scope :legislation, -> legislation_id { where(:legislation_id => legislation_id) }

 scope :search_query, lambda { |query|
    where(:number => "#{query}")
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^content/
      order("LOWER(articles.content) #{ direction }")        
    else
      raise(ArgumentError, "Opção inválida: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Nome (a-z)', 'name_asc']      
    ]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate_user!, except: [:api_request]

  # GET /articles
  # GET /articles.json
  def index
    if params[:filterrific].present?
      params[:filterrific][:search_query].each_char do |a|
        if not a =~ /[0-9]/
          params[:filterrific][:search_query].delete!(a)
        end
      end
    end
    @filterrific = initialize_filterrific(
      Article,
      params[:filterrific],
      select_options: {
        legislation: Legislation.all.collect {|a| [a.name, a.id]}
      }      
    ) or return    
    if @filterrific.find.length > 1
      @article = ""
    else
      @article = @filterrific.find
    end

    if not @article.empty?
      if @article.first.comments.present?
        @comments = []
        @authors = []
        @article.first.comments.each_with_index do |c, i|
          @comments[i] = File.read("#{Dir.pwd}/public/comments/#{@article.first.id}#{c.id}.txt")
          @authors[i] = c.author
        end
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    if @article.comments.present?
      @comments = []
      @comments_ids = []
      @authors = []
      @article.comments.each_with_index do |c, i|
        @comments[i] = File.read("#{Dir.pwd}/public/comments/#{@article.id}#{c.id}.txt")
        @comments_ids[i] = c.id
        @authors[i] = c.author
      end
    end    
  end

  def api_request
    params[:number].each_char do |a|
      if not a =~ /[0-9]/
        params[:number].delete!(a)
      end
    end
    @article = Article.where(:number => params[:number]).where(:legislation_id => params[:legislation]).first
    if @article.comments.present?
      @comments = []
      @authors = []
      @article.comments.each_with_index do |c, i|
        @comments[i] = File.read("#{Dir.pwd}/public/comments/#{@article.id}#{c.id}.txt")
        @authors[i] = c.author
      end
    end
    render :json => {:article => @article.content, :comments => @comments, :authors => @authors, number: @article.number}
  end

  # GET /articles/new
  def new
    @article = Article.new
    @article.build_comments
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create    
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_path_urlarticle, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_path_url, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.where(:number => params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:content, :legislation_id, :comments_attributes => [:content])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.haml
.container{style: "max-width:600px"}
  .card
    .card-body
      %h1 Editar Artigo
      %hr
      = render 'articles/shared/form'
      %hr
      = link_to fa_icon("arrow-left", text: "Voltar", style: "color:black"), articles_path, style: "color:black"

app/views/articles/index.html.haml
.container-fluid
  %div{style: "display:inline"}
    = form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' }, remote: false do |f|
      %div{style: "display:inline"}
        = f.text_field(                                |
            :search_query,                             |
            class: 'filterrific-periodically-observed form-control input-sm', |
            placeholder: 'Digite um artigo',            |
            style: "display: inline;max-width:70%"     |
          )                                            |
        
      %div{style: "display:inline"}
        = f.select(                                              |
          :legislation, @filterrific.select_options[:legislation], |
          { include_blank: true },                            |
          class: 'form-control input-sm',                       |
          style: "display: inline;max-width:20%"                |
        )                                                      |

        = f.submit 'Pesquisar', class: "btn btn-success" 

      = render_filterrific_spinner    

  %hr/

  = render(                           |
      partial: 'articles/shared/list',       |
      locals: { article: @article, comments: @comments, authors: @authors } |
    )                                 |
    

app/views/articles/index.js.erb
<%# app / views / articles / index.js.erb %>
<% js = escape_javascript(
    render(partial: 'articles/shared/list', locals: { articles: @articles })
) %>
    $("#filterrific_results").html("<%= js %>");

app/views/articles/new.html.haml
.login-form
  %h1 Novo Artigo
  %hr
  = render 'articles/shared/form'
  %hr
  = link_to fa_icon("arrow-left", text: "Voltar", style: "color:black"), articles_path, style: "color:black"

app/views/articles/show.html.haml
.container-fluid 
  .row
    .col-lg-3
      .card
        .card-header
          = Legislation.where(id: @article.legislation_id).first.name
        .card-body    
          = @article.content.gsub(/\n/, '<br>').html_safe
        - if current_user.role == "admin"
          .card-footer
            = link_to fa_icon('pencil', text: 'Editar', color: "#000"), edit_article_path(@article), style: "color:#000"
            = link_to fa_icon('trash', text: 'Excluir', color: "#000"), @article, method: :delete, data: { confirm: 'Tem certeza?' }, style: "color:#000", class: "pull-right"

    - @article.comments.each_with_index do |c, i|
      .col-lg-3
        .card
          .card-header
            = @authors[i]
          .card-body
            = (@comments[i]).html_safe
          - if current_user.role == "admin"    
            .card-footer
              = link_to fa_icon('pencil', text: 'Editar', color: "#000"), edit_comment_path(Comment.where(:id => @comments_ids[i]).first.id), style: "color:#000"
              = link_to fa_icon('trash', text: 'Excluir', color: "#000"), comment_path(Comment.where(:id => @comments_ids[i]).first), method: :delete, data: { confirm: 'Tem certeza?' }, style: "color:#000", class: "pull-right"