config/routes.rb
Rails.application.routes.draw do
  resources :archives
  devise_for :users
  root to: 'articles#index'

  resources :articles
  resources :legislations
  resources :users
  resources :comments

  get 'archives/:id/make_comments' => "archives#make_comments", as: :make_comments
  get 'archives/:id/make_articles' => "archives#make_articles", as: :make_articles

  get 'articles/API/:number/:legislation' => "articles#api_request", as: :retrieve_api_data
  get 'leg/API' => "legislations#api_request", as: :legislation_api_request

  get '/gil' => 'admin#index', as: :admin_path
end

app/models/legislation.rb
class Legislation < ApplicationRecord
  has_many :articles, dependent: :destroy
  accepts_nested_attributes_for :articles
end

app/controllers/legislations_controller.rb
class LegislationsController < ApplicationController
  before_action :set_legislation, only: [:show, :edit, :update, :destroy], except: [:api_request]
  before_action :authenticate_user!, except: [:api_request]
  # before_action :admin_only

  # GET /legislations
  # GET /legislations.json
  def index
    @legislations = Legislation.all
  end

  # GET /legislations/1
  # GET /legislations/1.json
  def show
  end
  
  def api_request
    @legislations = Legislation.all
    render :json => {:legislations => @legislations}    
  end

  # GET /legislations/new
  def new
    @legislation = Legislation.new
  end

  # GET /legislations/1/edit
  def edit
  end

  # POST /legislations
  # POST /legislations.json
  def create
    @legislation = Legislation.new(legislation_params)

    respond_to do |format|
      if @legislation.save
        format.html { redirect_to admin_path_url, notice: 'Legislation was successfully created.' }
        format.json { render :show, status: :created, location: @legislation }
      else
        format.html { render :new }
        format.json { render json: @legislation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legislations/1
  # PATCH/PUT /legislations/1.json
  def update
    respond_to do |format|
      if @legislation.update(legislation_params)
        format.html { redirect_to admin_path_url, notice: 'Legislation was successfully updated.' }
        format.json { render :show, status: :ok, location: @legislation }
      else
        format.html { render :edit }
        format.json { render json: @legislation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legislations/1
  # DELETE /legislations/1.json
  def destroy
    @legislation.destroy
    respond_to do |format|
      format.html { redirect_to admin_path_url, notice: 'Legislation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legislation
      @legislation = Legislation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legislation_params
      params.require(:legislation).permit(:name,
                                          :articles_attributes => [:content])
    end
end

app/helpers/legislations_helper.rb
module LegislationsHelper
end

app/views/legislations/edit.html.haml
.container{style: "max-width:600px"}
  .card
    .card-body
      %h1 Editar Legislação
      %hr
      = render 'legislations/shared/form'
      %hr
      = link_to fa_icon("arrow-left", style: "color:black", text: "Voltar"), legislations_path, style: "color:black"

app/views/legislations/index.html.haml
.container-fluid
  %h1 Legislações

  = render "legislations/shared/list", :legislations => @legislations
  %br

  = link_to 'Cadastrar legislação', new_legislation_path, class: "btn btn-primary"
  %hr.invisible
  = link_to fa_icon('arrow-left', text: "Voltar", style: "color:white"), '/', style: "color:white"

app/views/legislations/new.html.haml
.container{style: "max-width: 600px"}
  .card
    .card-body
      %h1 Cadastrar legislação
      %hr
      = render 'legislations/shared/form'
      %hr
      = link_to fa_icon("arrow-left", style: "color:black", text: "Voltar"), legislations_path, style: "color:black"

app/views/legislations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @legislation.name

= link_to 'Edit', edit_legislation_path(@legislation)
\|
= link_to 'Back', legislations_path